### ISSUE TITLE
Eff. = 0

### ISSUE THREAD

**Issue by nicobal** [axel3rd/mpg-coach-bot#101]
**Describe the bug**

Hello,

Maybe nothing or something that will correct itself later today but eff. is 0 for all my EPL players this morning.

Optimized team:
+---+---------------------+------+----+
| P |     Player name     | Eff. | Q. |
+---+---------------------+------+----+
| G | Fabianski Lukasz    | 0.00 | 25 |
| G | Heaton Tom          | 0.00 | 18 |
| G | Rui Patrício        | 0.00 | 15 |
+---+---------------------+------+----+
| D | Diop Issa           | 0.00 | 21 |
| D | Pieters Erik        | 0.00 | 13 |
| D | Guilbert Frederic   | 0.00 | 13 |
| D | Vestergaard Jannik  | 0.00 | 12 |
| D | Cuco Martina        | 0.00 | 12 |
| D | Stearman Richard    | 0.00 | 12 |
| D | Kiko Femenía        | 0.00 | 11 |
| D | Holebas José        | 0.00 | 10 |
| D | Engels Björn        | 0.00 | 10 |
| D | Angeliño            | 0.00 | 9  |
| D | Cédric Soares       | 0.00 | 9  |
| D | Dawson Craig        | 0.00 | 6  |
+---+---------------------+------+----+
| M | Ndombele Tanguy     | 0.00 | 22 |
| M | Kovacic Mateo       | 0.00 | 13 |
| M | Fornals Pablo       | 0.00 | 13 |
| M | Djenepo Moussa      | 0.00 | 12 |
| M | Trossard Leandro    | 0.00 | 11 |
| M | Zinchenko Oleksandr | 0.00 | 10 |
| M | Mount Mason         | 0.00 | 10 |
| M | Jota                | 0.00 | 7  |
| M | James Daniel        | 0.00 | 1  |
+---+---------------------+------+----+
| A | Jiménez Raúl        | 0.00 | 28 |
| A | Deulofeu Gerard     | 0.00 | 18 |
| A | Wesley              | 0.00 | 12 |
| A | Giroud Olivier      | 0.00 | 10 |
| A | El Ghazi Anwar      | 0.00 | 9  |
| A | Drmic Josip         | 0.00 | 8  |
+---+---------------------+------+----+

**Join debug files**

Depending your championship, join data files set in attachment.

1. The [MPG](https://mpg.football/) JSon *Response* of these *Request* on https://api.monpetitgazon.com (use the browser network monitor - F12, see wiki [Get MPG data for opening a bug](https://github.com/axel3rd/mpg-coach-bot/wiki/Get-MPG-data-for-opening-a-bug) for more details):

- From home : `GET /user/dashboard`
- From coach: `GET /league/[yourLeagueId]/coach`
- From transfer : `GET /league/[yourLeagueId]/transfer/buy`

2. The [Players statistics](https://www.mpgstats.fr/) data, one JSon from:

- https://www.mpgstats.fr/json/customteam.json/Ligue-1
- https://www.mpgstats.fr/json/customteam.json/Ligue-2
- https://www.mpgstats.fr/json/customteam.json/Premier-League
- https://www.mpgstats.fr/json/customteam.json/Liga
- https://www.mpgstats.fr/json/customteam.json/SerieA

3. The [Players statistics](https://www.mpgstats.fr/) time update data : https://www.mpgstats.fr/json/leagues.json

4. The [Injury / Suspended](http://www.equipeactu.fr/blessures-et-suspensions/fodbold/) data, one full HTML from:

- http://www.equipeactu.fr/blessures-et-suspensions/fodbold/france/ligue-1
- http://www.equipeactu.fr/blessures-et-suspensions/fodbold/france/ligue-2
- http://www.equipeactu.fr/blessures-et-suspensions/fodbold/angleterre/championship
- http://www.equipeactu.fr/blessures-et-suspensions/fodbold/espagne/primera-division
- http://www.equipeactu.fr/blessures-et-suspensions/fodbold/italie/serie-a

**Expected behavior**

If problem on *update team* feature, please join the *Request* and *Response* of `POST /league/[yourLeagueId]/coach` when you save your team in [MPG](https://mpg.football/).

**Comment by axel3rd** [comment]
@nicobal : Perhaps you run the program when *MPG Stats* has initiated *Day 1* with value to 0 for all players ?

I have checked now and I have the correct result, with same average as https://www.mpgstats.fr/top/Premier-League/custom for players which have not scored any goal this last weekend.

Ca you re-confirm this bug ? 

**NB** : There is a one our cache on these data => you can ensure no-cache by deleting any `mpg-coach-bot-*` files in directory:
- Windows: `%USERPROFILE%\AppData\Local\Temp` 
- Linux : `/tmp/`

**Comment by nicobal** [comment]
Oh I see now.
Yes, MPGStat has an average of 0 for EPL players right now. For Ligue 1, the average is the grade of the first game.

**Comment by axel3rd** [comment]
Humm ... from my side (France), when I access to https://www.mpgstats.fr/json/customteam.json/Premier-League, the England championship is up to date (day 1 with value > 0):

![image](https://user-images.githubusercontent.com/2912441/62875760-dfef0780-bd23-11e9-904c-d03e53062944.png)

**Comment by nicobal** [comment]
It works for me as well now!
