### ISSUE TITLE
Switch mpgstats API to new mlnstats API

### ISSUE THREAD

**Issue by axel3rd** [axel3rd/mpg-coach-bot#134]
See in @LittleLama in #98, mpgstats API will be updated.

Old endpoint:
```
https://www.mpgstats.fr/json/customteam.json/[LeagueName]
```

New endpoint:
```
https://api.mlnstats.com/leagues/[LeagueName]
```

Content seems change a little, to analyse.

**Comment by axel3rd** [comment]
@LittleLama : About new API usage (https://api.mlnstats.com/leagues/[LeagueName]), what is the new endpoint for https://www.mpgstats.fr/json/leagues.json (containing timestamp refresh) ?

Many thanks

**Comment by LittleLama** [comment]
New endpoint is api.mlnstats.com/builds

Le mer. 18 déc. 2019 à 13:55, Alix Lourme <notifications@github.com> a
écrit :

**Comment by axel3rd** [comment]
> New endpoint is api.mlnstats.com/builds

Many thanks !!

I work on API update, but it would be not very simple.
New API format have many changes, and to support old/new format in same time (to keep all historical unit tests OK) will be tricky.

**Comment by axel3rd** [comment]
@LittleLama : I will implement the new API like that, but I have some remarks (perhaps this is not a final implementation, ....).  This is in no way a criticism or request for change, just feedback about usage.

[1] In some Arrays (players list, player's stats by day), the items could be different types. First element is id (type int), the second element is the value/bean/object. It breaks (a little) the JSON key/value pairs principle and could occurs some difficulties in object deserialization (many language does not like when a list/array does not contain items of same type).

[2] The player stats by day is directly under player, and not under (average) stats like previous API.

### 

Sample with these 2 points: 
```
[
      1155,                               <--- ID / int as first array item
      {                                   <--- bean as second array item
        "n": "Neymar",
         ...
        "s": {
          "g": 7,
          ...
          "pa": 9
        },
        "p": [                             <--- Stats by days are not "under" previous stat bloc
          [
            -36,                           <--- Same "int" & "bean" in same array
            {
              "n": 7,
              "e": 3083,
              "g": 1
            }
          ],
          [
```

**Comment by LittleLama** [comment]
The format you point is a JS Map object. Really usefull to keep trace of
changes in the file and preserve unicity.

Yes stats are now only stats, perfs are basis of stats but stored in its
own property as a Map object. Negative days (first element) are about past
season, positive one's are about current season.

Le mer. 18 déc. 2019 à 22:19, Alix Lourme <notifications@github.com> a
écrit :

**Comment by axel3rd** [comment]
Hi @LittleLama, rencently the API format has changed. Now start with `"` (and not `{` as JSON format) and all double-quotes are escaped.

Sample with https://api.mlnstats.com/leagues/Premier-League:
```
"{\"bD\":\"2019-12-29T04:30:19.271Z\",\"mL\": ...
```

It will kept like that ? (The parsing change a little in this case)

Many thanks

**Comment by LittleLama** [comment]
Yeah I know. It doesnt really please to me. It makes no difference in JS
language but I need to check pros and cons of this format. Will be done
really quickly.

Le dim. 29 déc. 2019 à 16:28, Alix Lourme <notifications@github.com> a
écrit :

**Comment by axel3rd** [comment]
> Will be done really quickly

@LittleLama Ok, thanks. I will wait until any adapations. But I pomote pure JSon format, more common 😁.

**Comment by LittleLama** [comment]
Yes me too, consider it will be done like that.

Le dim. 29 déc. 2019 à 18:01, Alix Lourme <notifications@github.com> a
écrit :

**Comment by axel3rd** [comment]
> Yes me too, consider it will be done like that.

@LittleLama  Thx 👍
