### ISSUE TITLE
Use "auctions" for Mercato proposal (turn 1)

### ISSUE THREAD

**Issue by axel3rd** [axel3rd/mpg-coach-bot#139]
New MpgStats API (https://api.mlnstats.com/leagues/[LeagueName]) provides new statistics about **auctions**.

Sample for Neymar:

```
        "a": {
          "m": 35,
          "a": 67,
          "M": 154,
          "n": 30
        }
```
Details : Min:36 / Moy:67 / Max:154 / Nb: 30

It could be a very valuable value for transaction proposal.

----

@LittleLama : What is the source of these datas ? Are there real/valuable ? (I have tried to code a crawler on MPG Leagues as visitor, to retrieve price of players buy ... but not found how retrieve last real MPG league ids. 😁)

**Comment by LittleLama** [comment]
These are Mpgstats values of users selections. That's why auctions
occurrence are low.

Le mer. 18 déc. 2019 à 22:04, Alix Lourme <notifications@github.com> a
écrit :

**Comment by axel3rd** [comment]
@LittleLama : Thanks for precision. So it is perhaps not a really pertinent information (today) to display as correct value for buying a player 😢.

**Comment by axel3rd** [comment]
2 year after the reliability has increase significantly => should be include in Mercato proposal (with mention about turn 1).

**Comment by axel3rd** [comment]
API is existing for better "mean" by league player number, sample: https://api.mlnstats.com/player/auctions/28
But it could be a little violent due to the mercato number players proposal.
=> Stay on `"a"."a"` for first implementation.
