### ISSUE TITLE
Message on transactions proposal when last day stats have not fully reached

### ISSUE THREAD

**Issue by axel3rd** [axel3rd/mpg-coach-bot#157]
The day after weekend, the [MPG stats](http://mpgstats.fr/) could be not fully reached:

![image](https://user-images.githubusercontent.com/2912441/73661882-24d47500-469b-11ea-8b52-cdde5d3cf7d9.png)

There is an impact on transaction proposal, because statistics could be false for some players.

=> A message could be nice in this case.

**Comment by axel3rd** [comment]
In this cases, values are different here: 
![image](https://user-images.githubusercontent.com/2912441/74041039-31bbd600-49c5-11ea-923c-392ac92a4deb.png)

**WARN**: `cD` block could not exist on old version of stats.

**Comment by LittleLama** [comment]
Yes, all matches are not reported when lD is different from d.

Le ven. 7 févr. 2020 à 16:17, Alix Lourme <notifications@github.com> a
écrit :

**Comment by axel3rd** [comment]
> Yes, all matches are not reported when lD is different from d.

@LittleLama : At beginning of week I had the case ... but not (logically) currently.
I was waiting the next league day to check which item is lower to other and take data for unit tests ... I didn't remind ^^

**Comment by LittleLama** [comment]
d can be above lD

Le ven. 7 févr. 2020 à 17:27, Alix Lourme <notifications@github.com> a
écrit :

**Comment by axel3rd** [comment]
> d can be above lD

Many thx @LittleLama  !
