### ISSUE TITLE
Build fail : NotLinkException on mpg-coach-bot/target/test-classes/mpg.properties

### ISSUE THREAD

**Issue by mansuydejean** [axel3rd/mpg-coach-bot#184]
An exception is thrown when building if /mpg-coach-bot/target/test-classes/mpg.properties is not a symbolic link, but a real file
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-resources-plugin:3.2.0:testResources (default-testResources) on project mpg-coach-bot: /home/shoe/mpg-coach-bot/target/test-classes/mpg.properties -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-resources-plugin:3.2.0:testResources (default-testResources) on project mpg-coach-bot: /home/shoe/mpg-coach-bot/target/test-classes/mpg.properties
    ...
Caused by: org.apache.maven.plugin.MojoExecutionException: /home/shoe/mpg-coach-bot/target/test-classes/mpg.properties
    ...
Caused by: org.apache.maven.shared.filtering.MavenFilteringException: /home/shoe/mpg-coach-bot/target/test-classes/mpg.properties  
...
Caused by: java.nio.file.NotLinkException: /home/shoe/mpg-coach-bot/target/test-classes/mpg.properties

**Comment by mansuydejean** [comment]
If the file `mpg-coach-bot/target/test-classes/mpg.properties` is not a symbolic link, then build will fail.
This info could simply be added to the README.md

**Comment by axel3rd** [comment]
> If the file mpg-coach-bot/target/test-classes/mpg.properties is not a symbolic link, then build will fail.

Not sure to understand the use case with a symbolic link relation 🤔. 

**What is your scenario to produce the bug ?**

This snippet seems work correctly:
```shell
git clone https://github.com/axel3rd/mpg-coach-bot.git
cd mpg-coach-bot/
echo "fake" > src/test/resources/mpg.properties
mvn test-compile
```

**Comment by axel3rd** [comment]
@mansuydejean : is `/home/shoe/mpg-coach-bot` directory a symbolic link from somewhere ??

**Comment by mansuydejean** [comment]
`/home/shoe/mpg-coach-bot` is not a link but is a link `src/test/resources/mpg.properties` to `../../mpg.properties`

**Comment by axel3rd** [comment]
> but is a link src/test/resources/mpg.properties to ../../mpg.properties

Hummm, perhaps linked to [MRESOURCES-237](https://issues.apache.org/jira/browse/MRESOURCES-237), but released version plugin not available.

The most simple solution is perhaps NOT having a symlink here 😁 ?

**Comment by mansuydejean** [comment]
yes, perhaps... simply add a warning in README.md and we can close this
