### ISSUE TITLE
Proxy support

### ISSUE THREAD

**Issue by mansuydejean** [axel3rd/mpg-coach-bot#19]
It would be useful to have proxy support in the properties 

-  http proxy : host , port, username, password
-  httpS proxy : host , port, username, password

The best would be to relay the properties to the JVM (although I don't know how to do so)

**Comment by axel3rd** [comment]
Very valuable feature when you want manage your team the friday @work before going @home !
The best place is into `mpg.properties` IMO (reuse properties on command line is not really a good practice).

A workaround (without proxy authentication) could be to set parameters on `java` command line:

    -Dhttp.proxyHost=proxy.company.com -Dhttp.proxyPort=8080 -Dhttps.proxyHost=proxy.company.com -Dhttps.proxyPort=8080 

=> Planned on v1.1 - I would release official 1.0 soon, and implement a proxy in unit test to validate feature takes time (a little).

**Comment by axel3rd** [comment]
@mansuydejean : Testable on 1.1-SNAP in 5 minutes.
