### ISSUE TITLE
Manage Captain Bonus

### ISSUE THREAD

**Issue by axel3rd** [axel3rd/mpg-coach-bot#192]
A new **Captain bonus** is available on MPG, available for each matchs.
It should be managed and set automatically on "best player" if not already set manually.

But: **What is the best player for captain bonus ?**
1. The best middle-field player (in addition of UberEats bonus potentially, via `use.bonus` option) ; hoping increase the probability of some MPG goals ?
2. The goalkeeper ; hoping decrease some MPG goals ?

@mansuydejean / @LittleLama: What is your feeling about that: [1] / [2] / other ?

**Comment by axel3rd** [comment]
> But: What is the best player for captain bonus ?

Goalkeeper cannot be selected, it answers the question, it will be the best middle-field player 🤣

**Comment by LittleLama** [comment]
Good to know because I didn't have the answer 😂

Le mer. 4 août 2021 à 15:49, Alix Lourme ***@***.***> a
écrit :

**Comment by axel3rd** [comment]
JSon update sample: `/match-team-formation/mpg_match_team_formation_MLAX7HMK_3_1_1_5_6`

```json
{"composition":"343","playersOnPitch":{"1":"mpg_championship_player_45123","2":"mpg_championship_player_220237","3":"mpg_championship_player_52573","4":"mpg_championship_player_38580","5":"mpg_championship_player_195883","6":"mpg_championship_player_441240","7":"mpg_championship_player_159967","8":"mpg_championship_player_213940","9":"mpg_championship_player_162275","10":"mpg_championship_player_167443","11":"mpg_championship_player_168539","12":"mpg_championship_player_155335","13":"mpg_championship_player_437753","14":"mpg_championship_player_61170","15":"mpg_championship_player_240146","16":"mpg_championship_player_193454","17":"mpg_championship_player_482549","18":"mpg_championship_player_104407"},"tacticalSubs":[{"rating":5,"subId":"mpg_championship_player_155335","starterId":"mpg_championship_player_38580"},{"rating":5,"subId":"mpg_championship_player_61170","starterId":"mpg_championship_player_213940"},{"rating":5,"subId":"mpg_championship_player_240146","starterId":"mpg_championship_player_159967"},{"rating":6,"subId":"mpg_championship_player_193454","starterId":"mpg_championship_player_168539"}],"captain":"mpg_championship_player_195883"}
```
