### ISSUE TITLE
JDK 11 compatibility

### ISSUE THREAD

**Issue by mansuydejean** [axel3rd/mpg-coach-bot#20]
Currently it is not compatible with JDK 11 because javax.activation package is not in JDK 9

**Comment by mansuydejean** [comment]
https://stackoverflow.com/questions/46493613/what-is-the-replacement-for-javax-activation-package-in-java-9

**Comment by axel3rd** [comment]
This bug is mainly on JRE runtime => integration process should test all recent JDK: https://docs.travis-ci.com/user/languages/java/#using-java-10-and-later

**Comment by axel3rd** [comment]
Warning: Only distribution ZIP should be deployed on Travis JDK v1.8

**Comment by axel3rd** [comment]
Fixed by #25
