### ISSUE TITLE
Keep goalkeeper(s) if all injured/absents

### ISSUE THREAD

**Issue by mansuydejean** [axel3rd/mpg-coach-bot#227]
Si un des sites source d'infos déclare les gardiens inaptes, il y a un risque que ce ne soit pas le cas et de ne pas avoir de gardien.
J'ai eu le cas avec maligue2 je crois.
Il faudrait donc sélectionner quand-même les gardiens si a priori il n'y en a aucun apte.

**Comment by axel3rd** [comment]
@mansuydejean fixed in SNAPSHOT version (`mpg-coach-bot-1.9-20220228.110203-2.jar` from [packages](https://github.com/axel3rd/mpg-coach-bot/packages/))
