### ISSUE TITLE
Switch from to api.mlnstats.com to backend.mpgstats.fr

### ISSUE THREAD

**Issue by axel3rd** [axel3rd/mpg-coach-bot#265]
API endpoint `api.mlnstats.com` doesn't response anymore.
From https://www.mpgstats.fr website, the API backend seems to be `backend.mpgstats.fr`
=> Shouls be updated.

@LittleLama can you confirm ?

**Comment by LittleLama** [comment]
Hi
Api.mlnstats.com is.currently down because of IST network issue.
Backend is up and it's a good cached endpoint. 👍

Le dim. 24 nov. 2024, 00:58, Alix Lourme ***@***.***> a
écrit :

**Comment by axel3rd** [comment]
> Backend is up and it's a good cached endpoint. 👍

Many thanks @LittleLama for this confirmation.
I will let this new endpoint as sustainable.
