### ISSUE TITLE
Focus on recent efficiency 

### ISSUE THREAD

**Issue by axel3rd** [axel3rd/mpg-coach-bot#44]
On branch 1.2-SNAPSHOT for #40, the coefficient is strange

MpgStats is:

![image](https://user-images.githubusercontent.com/2912441/51064237-fe124f00-15fe-11e9-96eb-8f7571873a35.png)

MPG Datas for infos:

![image](https://user-images.githubusercontent.com/2912441/51064248-0c606b00-15ff-11e9-9824-8fb278985d9a.png)

And calulation is:

![image](https://user-images.githubusercontent.com/2912441/51064230-ea66e880-15fe-11e9-9131-e2827dbe4dfb.png)
 
Verratti scoring should be reviewed too ...

**Comment by axel3rd** [comment]
https://github.com/axel3rd/mpg-coach-bot/blob/9db51ccd09b57230ebfd3e35c793544ece1652ee/src/main/java/org/blondin/mpg/Main.java#L198

This formula is soo bad ... Sample with *Marco Varratti* today:

| **Method** | **Value** |
|-|-|
| p.getStats().getMatchs() | 12 |
| stats.getStats(championship).getDay() | 19 |
| p.getStats().getAverage() | 5.63 |
| p.getStats().getGoals() | 0 |

=> Result is : **3,56**.

So a good player who doesn't play often (injury ..)  is disadvantaged. The formula should be reviewed.

@mansuydejean : This is closely linked to #42 ...

**Comment by mansuydejean** [comment]
Any improvement on this one?

**Comment by axel3rd** [comment]
The **Efficiency coefficient** is implemented in v1.2 (see [Usage Advanced](https://github.com/axel3rd/mpg-coach-bot#usage-advanced)), but nothing about the player history (except average note).
I have not really idea about some algorithm/spec to implement.

**Comment by axel3rd** [comment]
@mansuydejean : I do not release 1.3 before a cuple of days. Some feedback appreciate on 1.3-SNAP (`efficiency.recent.focus` & `efficiency.recent.days`  options).

**Comment by axel3rd** [comment]
Reopen, because number of matchs used for stats is not the one configured but the current of season.
