### ISSUE TITLE
Auto-update team

### ISSUE THREAD

**Issue by axel3rd** [axel3rd/mpg-coach-bot#8]
With #2 & #1 implemented, an auto update can be done.

In configuration, an `update=[true|false]` (default `false` if not exist) properties should be implemented.

Technically, this is a `POST` on `/league/[leagueId]/coach` with content:
```
{
    "playersOnPitch": {
        "1": "player_42713",
        "2": "player_93605",
        ...
        "17": "player_219873",
        "18": null               <-- if no player seletect
    },
    "composition": 343,
    "tacticalsubstitutes": [
        {
            "subs": "player_183779",
            "start": "player_52782",
            "rating": 3
        },
        {
            "subs": "player_47654",
            "start": "player_213198",
            "rating": 3
        }
        ... until 5
    ],
    "bonusSelected": {
      ... should be investiguated --> should be the same as user selection
    },
    "matchId": "mpg_match_KLGXSSUG_1_6_4",
    "realday": 9
}

```

**Comment by axel3rd** [comment]
@mansuydejean / @megakopate : LGTM IMO but can you test 1.1-SNAPSHOT using `team.update = true` option with your team(s) ? Many thanks.

**Comment by mansuydejean** [comment]
I have not been able to debug it, but it is not working. My first team is a PL championship and I got an exception with a "400 bad request" right after the display of the optimized team

**Comment by axel3rd** [comment]
> I have not been able to debug it,

Hummm ... I should add content of response (if exist) in message when http code != 200 ; because currently it is hard to debug ...

https://github.com/axel3rd/mpg-coach-bot/blob/851d9c2491d6225de9cc692f4c9cc16b98758c66/src/main/java/org/blondin/mpg/AbstractClient.java#L111

**Comment by axel3rd** [comment]
@mansuydejean : Could you please re-test with 1.1-SNAP ? Hope to have more details on error. If not, I will add more debug on request content. Thanks

**Comment by axel3rd** [comment]
@mansuydejean : If no more infos, I propose you to open a "bug" with asked data files.

**Comment by axel3rd** [comment]
@mansuydejean : I want todo the v1.1 release => I close this one,. Don't hesitate to open a bug issue if problem occurs.
